FROM mcr.microsoft.com/dotnet/sdk:5.0

RUN mkdir /work/
WORKDIR /work

COPY ./src /work/
#RUN dotnet restore
#RUN dotnet restore MyUcbServiceTemplate.Api/MyUcbServiceTemplate.Api.csproj 
#RUN dotnet restore MyUcbServiceTemplate.Domain/MyUcbServiceTemplate.Domain.csproj
#RUN dotnet restore MyUcbServiceTemplate.Infrastructure/MyUcbServiceTemplate.Infrastructure.csproj
#RUN dotnet restore MyUcbServiceTemplate.Persistence/MyUcbServiceTemplate.Persistence.csproj
#RUN dotnet restore MyUcbServiceTemplate.Application/MyUcbServiceTemplate.Application.csproj
#RUN dotnet restore GrpcGreeterService/GrpcGreeterService.csproj

COPY ./src /work/
RUN mkdir /out/

#RUN dotnet publish --no-restore --output /out/ --configuration Release
RUN dotnet publish --output /out/ --configuration Release

